blank_issues_enabled: true
contact_links:
  - name: Dispatcharr Discord
    url: https://discord.com/channels/1340492560220684331/1487508974457589973
    about: General Dispatcharr plugin questions, support, or chatting with the community.
